# Generated by Django 6.0.1 on 2026-01-21 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_remove_affaire_client_remove_commande_affaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse_facturation', models.TextField(blank=True, null=True)),
                ('adresse_chantier', models.TextField(blank=True, null=True)),
                ('telephone_client', models.CharField(blank=True, max_length=20, null=True)),
                ('email_client', models.CharField(blank=True, max_length=254, null=True)),
                ('type_tiers', models.CharField(default='PARTICULIER', max_length=20)),
                ('siret', models.CharField(blank=True, max_length=14, null=True)),
                ('tva_intracommunautaire', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'commandes_client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nom_fournisseur', models.CharField(db_index=True, max_length=150)),
                ('nom_usage', models.CharField(blank=True, max_length=150, null=True)),
                ('code_fournisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('siret', models.CharField(blank=True, max_length=14, null=True)),
                ('tva_intracommunautaire', models.CharField(blank=True, max_length=20, null=True)),
                ('code_client', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commandes_fournisseur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreContact',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type_contact', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.client')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.fournisseur')),
            ],
            options={
                'db_table': 'core_contact',
                'managed': True,
            },
        ),
    ]
