# Generated by Django 6.0.1 on 2026-01-14 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_affaire_date_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='longueur_standard',
            field=models.IntegerField(blank=True, help_text='Longueur barre standard en mm', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='poids_kg_metre',
            field=models.FloatField(blank=True, help_text='Poids linéaire (kg/m)', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='surface_m2_metre',
            field=models.FloatField(blank=True, help_text='Surface de laquage (m²/m)', null=True),
        ),
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation_specifique', models.CharField(blank=True, max_length=255)),
                ('quantite', models.FloatField(default=0)),
                ('unite', models.CharField(default='U', max_length=20)),
                ('ral', models.CharField(blank=True, help_text='Couleur spécifique pour cet élément', max_length=50)),
                ('finition', models.CharField(blank=True, max_length=50)),
                ('longueur_commande', models.IntegerField(blank=True, help_text='Longueur à commander en mm (si débit)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('A_TRAITER', 'À Traiter'), ('VALIDE', 'Validé pour commande'), ('COMMANDE', 'Commandé'), ('EN_STOCK', 'Pris sur Stock')], default='A_TRAITER', max_length=20)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='core.affaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.article')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fournisseur')),
            ],
            options={
                'db_table': 'commandes_besoin',
                'managed': True,
            },
        ),
    ]
