# Generated by Django 6.0.1 on 2026-01-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_affaire_num_devis_remove_commande_num_arc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_livraison_confirmee',
        ),
    ]
