# Generated by Django 6.0.1 on 2026-01-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_commande_num_arc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='num_commande',
        ),
    ]
