# Generated by Django 6.0.1 on 2026-01-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_commande_num_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='code_article',
        ),
    ]
