# Generated by Django 6.0.1 on 2026-01-15 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_article_stock_alter_document_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreparametre',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Clé API Google Gemini (Prioritaire sur le .env)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'msg', 'eml'])]),
        ),
    ]
