# Generated by Django 6.0.1 on 2026-01-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_coreparametre_gemini_api_key_alter_document_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='conditionnement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Conditionnement'),
        ),
    ]
