# Generated by Django 6.0.1 on 2026-01-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_article_conditionnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fabricant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='article',
            name='ref_fabricant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Réf. Fabricant'),
        ),
        migrations.AddField(
            model_name='article',
            name='type_article',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type'),
        ),
    ]
