# Generated by Django 6.0.1 on 2026-01-16 06:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_article_fabricant_article_ref_fabricant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='prix_total_ht',
            new_name='total_ht',
        ),
        migrations.RenameField(
            model_name='lignecommande',
            old_name='prix_unitaire_ht',
            new_name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='code_article',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='finition',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='ral',
        ),
        migrations.AddField(
            model_name='besoin',
            name='statut_commande',
            field=models.CharField(blank=True, default='A COMMANDER', help_text='ex: A COMMANDER, EN COMMANDE', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='canal',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WEB', 'Web'), ('TELEPHONE', 'Téléphone'), ('AUTRE', 'Autre')], default='EMAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='document_arc',
            field=models.FileField(blank=True, null=True, upload_to='commandes/arc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='commande',
            name='document_bl',
            field=models.FileField(blank=True, null=True, upload_to='commandes/bl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(default='ACDIS', on_delete=django.db.models.deletion.PROTECT, to='core.fournisseur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='ref_externe_web',
            field=models.CharField(blank=True, help_text='N° de commande sur site fournisseur', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commande',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='besoin_generateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_commande_associee', to='core.besoin'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='designation',
            field=models.CharField(default='Ligne sans nom', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Remise en % ou montant ? Assumption: Montant or %? User said Decimal. Let's assume montant for now or %.", max_digits=5),
        ),
        migrations.AlterField(
            model_name='commande',
            name='affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affaire'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(blank=True, help_text="Date réelle de l'envoi", null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='designation',
            field=models.CharField(blank=True, help_text='Libellé commande', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_arc',
            field=models.CharField(blank=True, help_text='N° ARC Fournisseur', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_bdc',
            field=models.CharField(blank=True, help_text='N° BDC Interne', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_bl',
            field=models.CharField(blank=True, help_text='N° BL Fournisseur', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'En préparation'), ('ENVOYEE', 'Validée/Envoyée'), ('CONFIRME_ARC', 'ARC reçu et vérifié'), ('LIVREE_PARTIEL', 'BL reçu incomplet'), ('LIVREE', 'Tout est là'), ('FACTUREE', 'Terminée')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.article'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.commande'),
        ),
    ]
