# Generated by Django 6.0.1 on 2026-01-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_prix_total_ht_commande_total_ht_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ref_fournisseur',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom_fournisseur',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
