# Generated by Django 6.0.1 on 2026-01-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_article_ref_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreparametre',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='coreparametre',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='coreparametre',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='coreparametre',
            name='siret',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coreparametre',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='coreparametre',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='statut_ligne',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('LIVREE', 'Livrée'), ('RELIQUAT', 'Reliquat (Partiel)')], default='ATTENTE', max_length=20),
        ),
    ]
