# Generated by Django 6.0.1 on 2026-01-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_coreparametre_adresse_coreparametre_code_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaire',
            name='client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='affaire',
        ),
        migrations.RemoveField(
            model_name='document',
            name='affaire',
        ),
        migrations.RemoveField(
            model_name='besoin',
            name='affaire',
        ),
        migrations.RemoveField(
            model_name='article',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='article',
        ),
        migrations.RemoveField(
            model_name='prix',
            name='article',
        ),
        migrations.RemoveField(
            model_name='besoin',
            name='article',
        ),
        migrations.RemoveField(
            model_name='besoin',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='besoin_generateur',
        ),
        migrations.RemoveField(
            model_name='corecontact',
            name='client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='document',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='corecontact',
            name='fournisseur',
        ),
        migrations.RemoveConstraint(
            model_name='refcouleur',
            name='unique_ral_systeme',
        ),
        migrations.DeleteModel(
            name='RefCouleur',
        ),
        migrations.DeleteModel(
            name='Affaire',
        ),
        migrations.DeleteModel(
            name='Prix',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Besoin',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Lignecommande',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='CoreContact',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
