# Generated by Django 6.0.1 on 2026-01-21 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('tiers', '0001_initial'),
        ('core', '0017_remove_affaire_client_remove_commande_affaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_affaire', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('numero_prodevis', models.CharField(blank=True, max_length=50, null=True)),
                ('date_devis', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('EN_COURS', 'En Cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('total_achat_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_vente_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('adresse_facturation', models.TextField(blank=True, null=True)),
                ('adresse_chantier', models.TextField(blank=True, null=True)),
                ('num_facture', models.CharField(blank=True, max_length=50, null=True)),
                ('num_sav', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiers.client')),
            ],
            options={
                'db_table': 'commandes_affaire',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation_specifique', models.CharField(blank=True, max_length=255)),
                ('quantite', models.FloatField(default=0)),
                ('unite', models.CharField(default='U', max_length=20)),
                ('ral', models.CharField(blank=True, help_text='Couleur spécifique pour cet élément', max_length=50)),
                ('finition', models.CharField(blank=True, max_length=50)),
                ('longueur_commande', models.IntegerField(blank=True, help_text='Longueur à commander en mm (si débit)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('A_TRAITER', 'À Traiter'), ('VALIDE', 'Validé pour commande'), ('COMMANDE', 'Commandé'), ('EN_STOCK', 'Pris sur Stock')], default='A_TRAITER', max_length=20)),
                ('statut_commande', models.CharField(blank=True, default='A COMMANDER', help_text='ex: A COMMANDER, EN COMMANDE', max_length=20)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='ventes.affaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.article')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiers.fournisseur')),
            ],
            options={
                'db_table': 'commandes_besoin',
                'managed': True,
            },
        ),
    ]
