# Generated by Django 6.0.1 on 2026-01-21 18:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('tiers', '0001_initial'),
        ('ventes', '0001_initial'),
        ('core', '0017_remove_affaire_client_remove_commande_affaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('BROUILLON', 'En préparation'), ('ENVOYEE', 'Validée/Envoyée'), ('CONFIRME_ARC', 'ARC reçu et vérifié'), ('LIVREE_PARTIEL', 'BL reçu incomplet'), ('LIVREE', 'Tout est là'), ('FACTUREE', 'Terminée')], default='BROUILLON', max_length=20)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('WEB', 'Web'), ('TELEPHONE', 'Téléphone'), ('AUTRE', 'Autre')], default='EMAIL', max_length=20)),
                ('ref_externe_web', models.CharField(blank=True, help_text='N° de commande sur site fournisseur', max_length=100, null=True)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('document_arc', models.FileField(blank=True, null=True, upload_to='commandes/arc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('document_bl', models.FileField(blank=True, null=True, upload_to='commandes/bl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_commande', models.DateTimeField(blank=True, help_text="Date réelle de l'envoi", null=True)),
                ('designation', models.CharField(blank=True, help_text='Libellé commande', max_length=255, null=True)),
                ('numero_bdc', models.CharField(blank=True, help_text='N° BDC Interne', max_length=50, null=True)),
                ('numero_arc', models.CharField(blank=True, help_text='N° ARC Fournisseur', max_length=50, null=True)),
                ('numero_bl', models.CharField(blank=True, help_text='N° BL Fournisseur', max_length=50, null=True)),
                ('date_arc', models.DateField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateField(blank=True, null=True)),
                ('nb_produits_recus', models.IntegerField(default=0)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.affaire')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiers.fournisseur')),
            ],
            options={
                'db_table': 'commandes_commande',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.FloatField(default=1.0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('statut_ligne', models.CharField(choices=[('ATTENTE', 'En attente'), ('LIVREE', 'Livrée'), ('RELIQUAT', 'Reliquat (Partiel)')], default='ATTENTE', max_length=20)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.article')),
                ('besoin_generateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ligne_commande_associee', to='ventes.besoin')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.commande')),
            ],
            options={
                'db_table': 'commandes_lignecommande',
                'managed': True,
            },
        ),
    ]
