# Generated by Django 6.0.1 on 2026-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='json_data_arc',
            field=models.JSONField(blank=True, help_text="Extraction IA brute de l'ARC", null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='json_data_bl',
            field=models.JSONField(blank=True, help_text='Extraction IA brute du BL', null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut_verification',
            field=models.CharField(choices=[('PENDING', 'Non vérifié'), ('MISMATCH', 'Écarts détectés'), ('VALIDATED', 'Validé')], default='PENDING', max_length=20),
        ),
    ]
