# Generated by Django 6.0.1 on 2026-01-23 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_commande_json_data_arc_commande_json_data_bl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='document_bdc',
            field=models.FileField(blank=True, help_text='Bon de Commande Interne', null=True, upload_to='commandes/bdc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_arc',
            field=models.DateField(blank=True, help_text='Date réception ARC', null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(blank=True, help_text='Date envoi BDC', null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_livraison_prevue',
            field=models.DateField(blank=True, help_text="Extraite de l'ARC", null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_livraison_reelle',
            field=models.DateField(blank=True, help_text='Date réception BL', null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='document_arc',
            field=models.FileField(blank=True, help_text='Accusé de Réception', null=True, upload_to='commandes/arc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='document_bl',
            field=models.FileField(blank=True, help_text='Bon de Livraison', null=True, upload_to='commandes/bl/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYEE', 'Envoyée'), ('CONFIRME_ARC', 'Confirmée'), ('LIVREE', 'Livrée')], default='BROUILLON', max_length=20),
        ),
    ]
