# Generated by Django 6.0.1 on 2026-01-23 20:45

import apps.core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_commande_document_bdc_alter_commande_date_arc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='document_arc',
            field=models.FileField(blank=True, help_text='Accusé de Réception', null=True, upload_to=apps.core.utils.generate_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='document_bdc',
            field=models.FileField(blank=True, help_text='Bon de Commande Interne', null=True, upload_to=apps.core.utils.generate_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='commande',
            name='document_bl',
            field=models.FileField(blank=True, help_text='Bon de Livraison', null=True, upload_to=apps.core.utils.generate_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
    ]
