# Generated by Django 6.0.1 on 2026-01-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_alter_commande_document_arc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='document_arc',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='document_bdc',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='document_bl',
        ),
        migrations.AddField(
            model_name='commande',
            name='est_reliquat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='parent_commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reliquats', to='achats.commande'),
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_verrouilles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='prix_unitaire_facture',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix validé ARC/Facture', max_digits=10, null=True),
        ),
    ]
