from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from apps.tiers.models import Client, Fournisseur
from apps.core.forms import ClientForm, FournisseurForm
from apps.ged.services import generate_readable_id

@login_required
def client_list(request):
    queryset = Client.objects.all().order_by('nom')
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(nom__icontains=query) | 
            Q(email_client__icontains=query) |
            Q(ville__icontains=query)
        )
    
    paginator = Paginator(queryset, 50)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.headers.get('HX-Request'):
        return render(request, 'tiers/partials/client_table_body.html', {'page_obj': page_obj})

    return render(request, 'tiers/client_list.html', {'page_obj': page_obj})

@login_required
def client_edit(request, pk=None):
    if pk:
        client = get_object_or_404(Client, pk=pk)
    else:
        client = None

    if request.method == 'POST':
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            if not client: # Creation
                obj = form.save(commit=False)
                # Ensure ID (auto generated by text input usually, but let's be safe)
                if not obj.id:
                    clean_name = obj.nom.replace(' ', '').upper()[:5]
                    obj.id = f"CLI-{clean_name}"
                obj.save()
            else:
                form.save()
            
            messages.success(request, f"Client {form.instance.nom} enregistré.")
            return redirect('tiers:client_list')
    else:
        form = ClientForm(instance=client)

    if request.headers.get('HX-Request'):
         return render(request, 'tiers/partials/client_form_partial.html', {'form': form, 'is_htmx': True})

    return render(request, 'core/form_generic.html', {'form': form})

@login_required
def fournisseur_list(request):
    queryset = Fournisseur.objects.all().order_by('nom_fournisseur')
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(nom_fournisseur__icontains=query) | 
            Q(code_fournisseur__icontains=query) |
            Q(siret__icontains=query)
        )

    paginator = Paginator(queryset, 50)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.headers.get('HX-Request'):
        return render(request, 'tiers/partials/fournisseur_table_body.html', {'page_obj': page_obj})

    return render(request, 'tiers/fournisseur_list.html', {'page_obj': page_obj})

@login_required
def fournisseur_edit(request, pk=None):
    if pk:
        fournisseur = get_object_or_404(Fournisseur, pk=pk)
    else:
        fournisseur = None

    if request.method == 'POST':
        form = FournisseurForm(request.POST, request.FILES, instance=fournisseur)
        if form.is_valid():
            if not fournisseur: # Creation
                obj = form.save(commit=False)
                # Generation ID lisible moved to model save() usually, but here explicit
                obj.id = generate_readable_id(obj.nom_fournisseur, "FRN")
                obj.save()
                messages.success(request, f"Fournisseur {obj.nom_fournisseur} créé avec succès.")
            else:
                form.save()
                messages.success(request, f"Fournisseur {fournisseur.nom_fournisseur} modifié avec succès.")
            return redirect('tiers:fournisseur_list')
    else:
        form = FournisseurForm(instance=fournisseur)

    if request.headers.get('HX-Request'):
        return render(request, 'tiers/partials/fournisseur_form_partial.html', {'form': form, 'is_htmx': True})

    return render(request, 'core/form_generic.html', {'form': form})

@login_required
def fournisseur_delete(request, pk):
    fournisseur = get_object_or_404(Fournisseur, pk=pk)
    if request.method == "DELETE" or request.method == "POST":
        fournisseur.delete()
        messages.success(request, f"Fournisseur {fournisseur.nom_fournisseur} supprimé.")
        
        # Return updated list
        if request.headers.get('HX-Request'):
             # Note: Importing CoreContact might be needed if prefetch was used, but simple list for now
             queryset = Fournisseur.objects.all().order_by('nom_fournisseur')
             return render(request, 'tiers/partials/fournisseur_table_body.html', {'page_obj': Paginator(queryset, 50).page(1)})
             
        return redirect('tiers:fournisseur_list')
    return HttpResponse(status=405)
