# Generated by Django 6.0.1 on 2026-01-21 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        ('core', '0017_remove_affaire_client_remove_commande_affaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_fournisseur', models.CharField(db_index=True, max_length=100)),
                ('designation', models.CharField(max_length=255)),
                ('famille', models.CharField(max_length=100)),
                ('sous_famille', models.CharField(max_length=100)),
                ('lg', models.CharField(max_length=50)),
                ('unite', models.CharField(max_length=20)),
                ('conditionnement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conditionnement')),
                ('stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('fabricant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricant')),
                ('ref_fabricant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Réf. Fabricant')),
                ('type_article', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('poids_kg_metre', models.FloatField(blank=True, help_text='Poids linéaire (kg/m)', null=True)),
                ('surface_m2_metre', models.FloatField(blank=True, help_text='Surface de laquage (m²/m)', null=True)),
                ('longueur_standard', models.IntegerField(blank=True, help_text='Longueur barre standard en mm', null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiers.fournisseur')),
            ],
            options={
                'db_table': 'commandes_article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('prix_nouveau', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ancien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_nouveau_prix', models.DateField()),
                ('date_ancien_prix', models.DateField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.article')),
            ],
            options={
                'db_table': 'commandes_prix',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefCouleur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ral', models.CharField(max_length=50)),
                ('nom_couleur', models.CharField(max_length=100)),
                ('systeme', models.CharField(choices=[('INSTALLUX', 'Installux'), ('SCHUCO', 'Schüco'), ('STANDARD', 'Standard'), ('AUTRE', 'Autre')], max_length=50)),
                ('code_mat', models.CharField(blank=True, help_text='Ex: EM ou M', max_length=20, null=True)),
                ('code_sable', models.CharField(blank=True, help_text='Ex: SM ou S', max_length=20, null=True)),
                ('code_brillant', models.CharField(blank=True, help_text='Ex: B', max_length=20, null=True)),
            ],
            options={
                'db_table': 'core_ref_couleur',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('ral', 'systeme'), name='unique_ral_systeme')],
            },
        ),
    ]
