# Generated by Django 6.0.1 on 2026-01-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prix',
            name='article',
        ),
        migrations.RemoveConstraint(
            model_name='refcouleur',
            name='unique_ral_systeme',
        ),
        migrations.DeleteModel(
            name='RefCouleur',
        ),
        migrations.DeleteModel(
            name='Prix',
        ),
    ]
