# Generated by Django 6.0.1 on 2026-01-12 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse_facturation', models.TextField(blank=True, null=True)),
                ('adresse_chantier', models.TextField(blank=True, null=True)),
                ('telephone_client', models.CharField(blank=True, max_length=20, null=True)),
                ('email_client', models.CharField(blank=True, max_length=254, null=True)),
                ('type_tiers', models.CharField(default='PARTICULIER', max_length=20)),
                ('siret', models.CharField(blank=True, max_length=14, null=True)),
                ('tva_intracommunautaire', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'commandes_client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreParametre',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nom_societe', models.CharField(max_length=100)),
                ('chemin_stockage_local', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'core_parametre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('nom_fournisseur', models.CharField(max_length=150)),
                ('nom_usage', models.CharField(blank=True, max_length=150, null=True)),
                ('code_fournisseur', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('siret', models.CharField(blank=True, max_length=14, null=True)),
                ('tva_intracommunautaire', models.CharField(blank=True, max_length=20, null=True)),
                ('code_client', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commandes_fournisseur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_affaire', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('numero_prodevis', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('EN_COURS', 'En Cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('total_achat_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_vente_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('adresse_facturation', models.TextField(blank=True, null=True)),
                ('adresse_chantier', models.TextField(blank=True, null=True)),
                ('num_devis', models.CharField(blank=True, max_length=50, null=True)),
                ('num_facture', models.CharField(blank=True, max_length=50, null=True)),
                ('num_sav', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.client')),
            ],
            options={
                'db_table': 'commandes_affaire',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('prix_total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_commande', models.DateField(blank=True, null=True)),
                ('date_arc', models.DateField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateField(blank=True, null=True)),
                ('date_livraison_confirmee', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('COMMANDE', 'Commande'), ('CONFIRME_ARC', 'Confirmé ARC'), ('LIVRE', 'Livré')], default='BROUILLON', max_length=20)),
                ('num_arc', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_arc', models.CharField(blank=True, max_length=50, null=True)),
                ('num_bl', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_bl', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_bdc', models.CharField(blank=True, max_length=50, null=True)),
                ('nb_produits_recus', models.IntegerField(default=0)),
                ('num_commande', models.CharField(blank=True, max_length=50, null=True)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.affaire')),
            ],
            options={
                'db_table': 'commandes_commande',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_document', models.CharField(blank=True, choices=[('DEVIS_CLIENT', 'Devis Client'), ('BON_COMMANDE', 'Bon de Commande'), ('ARC_FOURNISSEUR', 'ARC Fournisseur'), ('BON_LIVRAISON', 'Bon de Livraison')], max_length=100, null=True)),
                ('date_document', models.DateField(blank=True, null=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.affaire')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.commande')),
            ],
            options={
                'db_table': 'documents_document',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoreContact',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type_contact', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.client')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.fournisseur')),
            ],
            options={
                'db_table': 'core_contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_fournisseur', models.CharField(max_length=100)),
                ('code_article', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(max_length=255)),
                ('famille', models.CharField(max_length=100)),
                ('sous_famille', models.CharField(max_length=100)),
                ('lg', models.CharField(max_length=50)),
                ('unite', models.CharField(max_length=20)),
                ('conditionnement', models.CharField(max_length=50)),
                ('stock', models.FloatField(default=0.0)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.fournisseur')),
            ],
            options={
                'db_table': 'commandes_article',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lignecommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.FloatField(default=1.0)),
                ('couleur_ral', models.CharField(blank=True, max_length=50, null=True)),
                ('ral', models.CharField(blank=True, max_length=50, null=True)),
                ('finition', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('code_article', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.commande')),
            ],
            options={
                'db_table': 'commandes_lignecommande',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('prix_nouveau', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_ancien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_nouveau_prix', models.DateField()),
                ('date_ancien_prix', models.DateField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.article')),
            ],
            options={
                'db_table': 'commandes_prix',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefCouleur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ral', models.CharField(max_length=50)),
                ('nom_couleur', models.CharField(max_length=100)),
                ('systeme', models.CharField(choices=[('INSTALLUX', 'Installux'), ('SCHUCO', 'Schüco'), ('STANDARD', 'Standard'), ('AUTRE', 'Autre')], max_length=50)),
                ('code_mat', models.CharField(blank=True, help_text='Ex: EM ou M', max_length=20, null=True)),
                ('code_sable', models.CharField(blank=True, help_text='Ex: SM ou S', max_length=20, null=True)),
                ('code_brillant', models.CharField(blank=True, help_text='Ex: B', max_length=20, null=True)),
            ],
            options={
                'db_table': 'core_ref_couleur',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('ral', 'systeme'), name='unique_ral_systeme')],
            },
        ),
    ]
