# Generated by Django 6.0.1 on 2026-01-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affaire',
            name='date_devis',
            field=models.DateField(blank=True, null=True),
        ),
    ]
