<?php
// tools/apex_schema_scanner.php - ZERO HALLUCINATION SCHEMA VERIFICATION
require_once __DIR__ . '/../db.php';

echo "<h1>💎 APEX INTEGRITY - Schema Scanner</h1>";
echo "<p>Scanning ALL tables used by dashboard...</p>";

$tables = [
    'commandes_achats',
    'affaires', 
    'clients',
    'fournisseurs',
    'metrage_interventions',
    'rendez_vous'
];

$schema_map = [];

foreach($tables as $table) {
    echo "<h2>Table: $table</h2>";
    
    try {
        $stmt = $pdo->query("DESCRIBE $table");
        $columns = $stmt->fetchAll();
        
        $schema_map[$table] = [];
        
        echo "<table class='table table-sm table-bordered'>";
        echo "<tr><th>Field</th><th>Type</th><th>Null</th><th>Key</th><th>Default</th></tr>";
        
        foreach($columns as $col) {
            $schema_map[$table][] = $col['Field'];
            
            $key_badge = '';
            if($col['Key'] === 'PRI') $key_badge = '<span class="badge bg-primary">PRI</span>';
            if($col['Key'] === 'MUL') $key_badge = '<span class="badge bg-info">FK</span>';
            
            echo "<tr>";
            echo "<td><code>{$col['Field']}</code></td>";
            echo "<td>{$col['Type']}</td>";
            echo "<td>{$col['Null']}</td>";
            echo "<td>$key_badge</td>";
            echo "<td>" . ($col['Default'] ?? 'NULL') . "</td>";
            echo "</tr>";
        }
        echo "</table>";
        
    } catch(PDOException $e) {
        echo "<div class='alert alert-danger'>ERROR: {$e->getMessage()}</div>";
    }
}

// Generate PHP constant file
echo "<h2>📋 Generated Schema Constants</h2>";
echo "<pre>";
echo "<?php\n";
echo "// AUTO-GENERATED BY APEX SCANNER - DO NOT EDIT MANUALLY\n";
echo "// Generated: " . date('Y-m-d H:i:s') . "\n\n";

foreach($schema_map as $table => $columns) {
    $const_name = strtoupper($table) . '_COLUMNS';
    echo "const $const_name = [\n";
    foreach($columns as $col) {
        echo "    '$col',\n";
    }
    echo "];\n\n";
}
echo "</pre>";

// Save to file
$php_code = "<?php\n";
$php_code .= "// AUTO-GENERATED BY APEX SCANNER - DO NOT EDIT MANUALLY\n";
$php_code .= "// Generated: " . date('Y-m-d H:i:s') . "\n\n";

foreach($schema_map as $table => $columns) {
    $const_name = strtoupper($table) . '_COLUMNS';
    $php_code .= "const $const_name = [\n";
    foreach($columns as $col) {
        $php_code .= "    '$col',\n";
    }
    $php_code .= "];\n\n";
}

file_put_contents(__DIR__ . '/schema_constants.php', $php_code);

echo "<div class='alert alert-success'>";
echo "<h4>✅ Schema Scan Complete</h4>";
echo "<p>Schema constants saved to: <code>tools/schema_constants.php</code></p>";
echo "<p>Use these constants to prevent column name hallucinations.</p>";
echo "</div>";
