<?php
// AUTO-GENERATED BY APEX SCANNER - DO NOT EDIT MANUALLY
// Generated: 2026-01-02 12:07:47

const COMMANDES_ACHATS_COLUMNS = [
    'id',
    'fournisseur_id',
    'affaire_id',
    'ref_interne',
    'ref_arc_fournisseur',
    'date_commande',
    'date_prevue_cible',
    'precision_date',
    'date_livraison_reelle',
    'statut',
    'lieu_livraison',
    'chemin_pdf_bdc',
    'chemin_pdf_arc',
    'source_donnees',
    'statut_ia',
    'raw_text_analyse',
    'date_en_attente',
    'date_arc_recu',
    'date_livraison_prevue',
    'designation',
];

const AFFAIRES_COLUMNS = [
    'id',
    'client_id',
    'numero_prodevis',
    'nom_affaire',
    'statut',
    'chemin_dossier_ged',
    'date_pose_debut',
    'date_pose_fin',
    'equipe_pose',
    'statut_chantier',
    'date_creation',
    'montant_ht',
    'date_signature',
];

const CLIENTS_COLUMNS = [
    'id',
    'civilite',
    'nom_principal',
    'prenom',
    'code_client',
    'email_principal',
    'telephone_fixe',
    'telephone_mobile',
    'adresse_postale',
    'code_postal',
    'ville',
    'pays',
    'notes',
    'commentaire',
    'date_creation',
];

const FOURNISSEURS_COLUMNS = [
    'id',
    'nom',
    'code_fou',
    'code_client_chez_eux',
    'email_commande',
    'adresse_postale',
    'code_postal',
    'ville',
    'pays',
    'siret',
    'tva_intra',
    'site_web',
    'notes',
    'condition_paiement',
    'delai_habituel_jours',
    'jour_livraison_fixe',
    'franco_port',
    'categorie_cout',
    'adresse_enlevement',
    'site_web_pro',
];

const METRAGE_INTERVENTIONS_COLUMNS = [
    'id',
    'affaire_id',
    'date_prevue',
    'date_realisee',
    'statut',
    'technicien_id',
    'infos_acces',
    'notes_generales',
    'gps_lat',
    'gps_lon',
    'created_at',
    'updated_at',
];

const RENDEZ_VOUS_COLUMNS = [
    'id',
    'affaire_id',
    'type',
    'date_rdv',
    'heure_debut',
    'heure_fin',
    'statut',
    'notes',
    'created_at',
];

