# Generated by Django 6.0.1 on 2026-01-21 18:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        ('ventes', '0001_initial'),
        ('core', '0017_remove_affaire_client_remove_commande_affaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'msg', 'eml'])])),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_document', models.CharField(blank=True, choices=[('DEVIS_CLIENT', 'Devis Client'), ('BON_COMMANDE', 'Bon de Commande'), ('ARC_FOURNISSEUR', 'ARC Fournisseur'), ('BON_LIVRAISON', 'Bon de Livraison')], max_length=100, null=True)),
                ('date_document', models.DateField(blank=True, null=True)),
                ('affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.affaire')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achats.commande')),
            ],
            options={
                'db_table': 'documents_document',
                'managed': True,
            },
        ),
    ]
