# Generated by Django 6.0.1 on 2026-01-23 20:45

import apps.core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to=apps.core.utils.generate_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'msg', 'eml'])]),
        ),
    ]
