# Generated by Django 6.0.1 on 2026-01-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_remove_commande_document_arc_and_more'),
        ('ged', '0002_alter_document_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='est_actif',
            field=models.BooleanField(default=True, help_text='Est la version courante de ce type de doc'),
        ),
        migrations.AlterField(
            model_name='document',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='achats.commande'),
        ),
    ]
