# Generated by Django 6.0.1 on 2026-01-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_longueur_standard_article_poids_kg_metre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaire',
            name='num_devis',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='num_arc',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='num_bl',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='numero_arc',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='couleur_ral',
        ),
    ]
