# Generated by Django 6.0.1 on 2026-01-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_commande_date_livraison_confirmee'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='num_arc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_arc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
