<!-- views/modules/commande_rapide/form_pliage.php -->
<div class="card shadow border-0 animate__animated animate__fadeIn">
    <div class="card-header bg-dark text-white py-2 d-flex justify-content-between align-items-center">
        <h5 class="mb-0 fw-bold"><i class="fas fa-shapes me-2"></i>COMMANDE PLIAGE / TÔLERIE</h5>
        <button type="button" class="btn btn-sm btn-close btn-close-white" onclick="document.getElementById('form_container').innerHTML=''; document.getElementById('form_container').style.display='none';"></button>
    </div>
    <div class="card-body p-4">
        <form id="form_pliage" onsubmit="return false;">
            <input type="hidden" name="module_type" value="PLIAGE">
            
            <div class="row g-4">
                
                <!-- 1. MATIÈRE -->
                <div class="col-md-3">
                    <label class="form-label fw-bold small text-uppercase">Matière</label>
                    <select class="form-select" name="matiere">
                        <option value="ALU_15">Alu 15/10e (Standard)</option>
                        <option value="ALU_20">Alu 20/10e (Rigide)</option>
                        <option value="ACIER_LAQUE">Acier Laqué</option>
                        <option value="INOX">Inox</option>
                    </select>
                </div>

                <div class="col-md-3">
                    <label class="form-label fw-bold small text-uppercase">Couleur / RAL</label>
                    <select class="form-select" name="ral">
                        <option value="7016_SAT">RAL 7016 Satiné (Anthracite)</option>
                        <option value="9010_BRI">RAL 9010 Brillant (Blanc)</option>
                        <option value="9005_SAT">RAL 9005 Satiné (Noir)</option>
                        <option value="ANODISE">Anodisé Naturel</option>
                        <option value="AUTRE">Autre (Préciser)</option>
                    </select>
                </div>
                
                <div class="col-md-6 border-start">
                     <label class="form-label fw-bold small text-uppercase mb-3">Forme (Cliquer pour choisir)</label>
                     <div class="d-flex gap-2 justify-content-start flex-wrap">
                         
                         <label class="btn btn-outline-secondary p-2 shadow-sm">
                             <input type="radio" class="btn-check" name="forme_code" value="L" checked onchange="setPliageShape('L')">
                             <span class="d-block"><i class="fas fa-caret-left fa-2x"></i></span>
                             <span class="small fw-bold">Cornière (L)</span>
                         </label>

                         <label class="btn btn-outline-secondary p-2 shadow-sm">
                             <input type="radio" class="btn-check" name="forme_code" value="U" onchange="setPliageShape('U')">
                             <span class="d-block"><i class="fas fa-arrows-alt-h fa-2x"></i></span>
                             <span class="small fw-bold">Coulisse (U)</span>
                         </label>

                         <label class="btn btn-outline-secondary p-2 shadow-sm">
                             <input type="radio" class="btn-check" name="forme_code" value="Z" onchange="setPliageShape('Z')">
                             <span class="d-block"><i class="fas fa-bolt fa-2x"></i></span>
                             <span class="small fw-bold">Bavette (Z)</span>
                         </label>

                         <label class="btn btn-outline-secondary p-2 shadow-sm">
                             <input type="radio" class="btn-check" name="forme_code" value="PLAT" onchange="setPliageShape('PLAT')">
                             <span class="d-block"><i class="fas fa-minus fa-2x"></i></span>
                             <span class="small fw-bold">Plat</span>
                         </label>
                     </div>
                </div>

                <div class="col-12"><hr></div>

                <!-- 2. CANVAS DESIGNER -->
                <div class="col-md-5">
                    <h6 class="fw-bold text-primary mb-3">Paramètres Dimensionnels (mm)</h6>
                    
                    <div id="inputs_container">
                        <!-- Dynamic Inputs generated by JS -->
                        <div class="mb-2 input-row">
                            <label class="form-label small">Cote A (mm)</label>
                            <input type="number" class="form-control" id="cote_A" value="50" oninput="drawPliage()">
                        </div>
                        <div class="mb-2 input-row">
                            <label class="form-label small">Cote B (mm)</label>
                            <input type="number" class="form-control" id="cote_B" value="50" oninput="drawPliage()">
                        </div>
                        <!-- More inputs C, D, Angle populated by JS -->
                    </div>

                    <div class="mt-3">
                         <label class="form-label fw-bold small text-uppercase">Face Laquée</label>
                         <div class="btn-group w-100 btn-group-sm">
                             <input type="radio" class="btn-check" name="laquage_side" id="laq_ext" value="EXT" checked onchange="drawPliage()">
                             <label class="btn btn-outline-primary" for="laq_ext">Extérieure</label>

                             <input type="radio" class="btn-check" name="laquage_side" id="laq_int" value="INT" onchange="drawPliage()">
                             <label class="btn btn-outline-primary" for="laq_int">Intérieure</label>
                         </div>
                         <div class="form-text small">Indiqué par le trait rouge sur le croquis.</div>
                    </div>

                    <div class="mt-4">
                        <label class="form-label fw-bold small">Quantité</label>
                        <input type="number" class="form-control fw-bold" name="quantite" value="1" required>
                    </div>
                </div>

                <div class="col-md-7 text-center">
                    <div class="border rounded bg-white shadow-inner p-3 d-flex justify-content-center align-items-center" style="height: 350px; background-image: radial-gradient(#e5e5e5 1px, transparent 1px); background-size: 20px 20px;">
                        <canvas id="pliageCanvas" width="400" height="300"></canvas>
                    </div>
                    <div class="small text-muted mt-2 fst-italic">Croquis généré dynamiquement</div>
                </div>

                <div class="col-12 mt-4 text-center">
                    <button type="button" class="btn btn-dark btn-lg rounded-pill px-5 shadow" onclick="submitModule('form_pliage')">
                        <i class="fas fa-check-circle me-2"></i>COMMANDER PLIAGE
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
